/* Generated By:JavaCC: Do not edit this line. PreprocessorConstants.java */
package wml;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PreprocessorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DEFINE = 2;
  /** RegularExpression Id. */
  int ENDDEF = 3;
  /** RegularExpression Id. */
  int IFDEF = 4;
  /** RegularExpression Id. */
  int ENDIF = 5;
  /** RegularExpression Id. */
  int UNDEF = 6;
  /** RegularExpression Id. */
  int TEXTDOMAIN = 7;
  /** RegularExpression Id. */
  int LBR = 8;
  /** RegularExpression Id. */
  int RBR = 9;
  /** RegularExpression Id. */
  int LSB = 10;
  /** RegularExpression Id. */
  int RSB = 11;
  /** RegularExpression Id. */
  int EQL = 12;
  /** RegularExpression Id. */
  int SLASH = 13;
  /** RegularExpression Id. */
  int SPACE = 14;
  /** RegularExpression Id. */
  int STAG = 15;
  /** RegularExpression Id. */
  int ETAG = 16;
  /** RegularExpression Id. */
  int PATH = 17;
  /** RegularExpression Id. */
  int STRING = 18;
  /** RegularExpression Id. */
  int NUMBER = 19;
  /** RegularExpression Id. */
  int LETTER = 20;
  /** RegularExpression Id. */
  int DIGIT = 21;
  /** RegularExpression Id. */
  int EOL = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\"#define\"",
    "\"#enddef\"",
    "\"#ifdef\"",
    "\"#endif\"",
    "\"#undef\"",
    "\"#textdomain\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\"/\"",
    "<SPACE>",
    "<STAG>",
    "<ETAG>",
    "<PATH>",
    "<STRING>",
    "<NUMBER>",
    "<LETTER>",
    "<DIGIT>",
    "<EOL>",
  };

}
