/* Generated By:JavaCC: Do not edit this line. PreprocessorConstants.java */
package wml;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PreprocessorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ANGLE_OPEN = 1;
  /** RegularExpression Id. */
  int ANGLE_CLOSE = 3;
  /** RegularExpression Id. */
  int DEFINE = 4;
  /** RegularExpression Id. */
  int ENDDEF = 5;
  /** RegularExpression Id. */
  int IFDEF = 6;
  /** RegularExpression Id. */
  int ENDIF = 7;
  /** RegularExpression Id. */
  int UNDEF = 8;
  /** RegularExpression Id. */
  int TEXTDOMAIN = 9;
  /** RegularExpression Id. */
  int LBR = 10;
  /** RegularExpression Id. */
  int RBR = 11;
  /** RegularExpression Id. */
  int LSB = 12;
  /** RegularExpression Id. */
  int RSB = 13;
  /** RegularExpression Id. */
  int LPAR = 14;
  /** RegularExpression Id. */
  int RPAR = 15;
  /** RegularExpression Id. */
  int LANGLE = 16;
  /** RegularExpression Id. */
  int RANGLE = 17;
  /** RegularExpression Id. */
  int EQL = 18;
  /** RegularExpression Id. */
  int SLASH = 19;
  /** RegularExpression Id. */
  int HASH = 20;
  /** RegularExpression Id. */
  int SPACE = 21;
  /** RegularExpression Id. */
  int QUOTED_STRING = 22;
  /** RegularExpression Id. */
  int INBLK = 23;
  /** RegularExpression Id. */
  int STAG = 24;
  /** RegularExpression Id. */
  int ETAG = 25;
  /** RegularExpression Id. */
  int PATH = 26;
  /** RegularExpression Id. */
  int STRING = 27;
  /** RegularExpression Id. */
  int MARG = 28;
  /** RegularExpression Id. */
  int NUMBER = 29;
  /** RegularExpression Id. */
  int LETTER = 30;
  /** RegularExpression Id. */
  int DIGIT = 31;
  /** RegularExpression Id. */
  int EOL = 32;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int ANGLE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"<<\"",
    "<token of kind 2>",
    "\">>\"",
    "\"define\"",
    "\"enddef\"",
    "\"ifdef\"",
    "\"endif\"",
    "\"undef\"",
    "\"textdomain\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"<\"",
    "\">\"",
    "\"=\"",
    "\"/\"",
    "\"#\"",
    "<SPACE>",
    "<QUOTED_STRING>",
    "<INBLK>",
    "<STAG>",
    "<ETAG>",
    "<PATH>",
    "<STRING>",
    "<MARG>",
    "<NUMBER>",
    "<LETTER>",
    "<DIGIT>",
    "<EOL>",
  };

}
