package com.babai.wml.utils;

import java.lang.annotation.*;

/**
 * Marks code as generated by AI.
 */
@Retention(RetentionPolicy.CLASS)
@Target({ElementType.TYPE, ElementType.METHOD, ElementType.FIELD})
public @interface AIGenerated {
	String value() default "This class is generated by AI";
}
